export const dummyBooks = [
  {
    id: 1,
    title: "Panduan Lengkap Budidaya Hidroponik",
    slug: "panduan-hidroponik",
    author: "Tim Pertanian Desa",
    category: "Pertanian",
    cover_image: "https://images.unsplash.com/photo-1599818815147-380d3ce30d95?q=80&w=400&auto=format&fit=crop",
    stock: 5,
  },
  {
    id: 2,
    title: "Sejarah Majapahit dan Nusantara",
    slug: "sejarah-majapahit",
    author: "Ahmad Zainudin",
    category: "Sejarah",
    cover_image: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=400&auto=format&fit=crop",
    stock: 2,
  },
  {
    id: 3,
    title: "Laskar Pelangi",
    slug: "laskar-pelangi",
    author: "Andrea Hirata",
    category: "Fiksi",
    cover_image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=400&auto=format&fit=crop",
    stock: 0,
  },
  {
    id: 4,
    title: "Cara Memulai UMKM di Era Digital",
    slug: "umkm-digital",
    author: "Budi Santoso",
    category: "Ekonomi",
    cover_image: "https://images.unsplash.com/photo-1553484771-371a605b060b?q=80&w=400&auto=format&fit=crop",
    stock: 3,
  },
];
